// src/routes/programs/control_panel.jsx
import { For } from "solid-js";
import { setQueueProgram } from "../../lib/store";

export default function ControlPanel() {
  const items = [
    {
      name: "Display",
      icon: "/images/xp/icons/DisplayProperties.png",
      path: "./programs/display_properties.jsx"
    },
    {
      name: "Network",
      icon: "/images/xp/icons/NetworkConnections.png",
      path: "./programs/network_status.jsx"
    },
    {
      name: "Windows Update",
      icon: "/images/xp/icons/WindowsUpdate.png",
      path: "./programs/windows_update.jsx"
    },
    {
      name: "Safely Remove Hardware",
      icon: "/images/xp/icons/SafelyRemoveHardware.png",
      path: "./programs/safely_remove_hardware.jsx"
    }
  ];

  return (
    <div class="p-4">
      <div class="grid grid-cols-2 sm:grid-cols-3 gap-4 text-xs">
        <For each={items}>{(item) => (
          <div
            class="flex flex-col items-center text-center cursor-pointer select-none p-2 hover:bg-[rgb(122,150,223)] hover:text-white rounded"
            onClick={() =>
              setQueueProgram({
                name: item.name,
                icon: item.icon,
                path: item.path
              })
            }
          >
            <img
              src={item.icon}
              alt={item.name}
              width="32"
              height="32"
              class="pointer-events-none"
            />
            <span class="mt-2">{item.name}</span>
          </div>
        )}</For>
      </div>
    </div>
  );
}

// src/routes/xp/programs/control_panel.svelte
<script>
    import Window from '../../../lib/components/xp/Window.svelte';
    import { runningPrograms, queueProgram } from '../../../lib/store';

    export let id;
    export let window;
    export let self;
    export let exec_path;

    export function destroy(){
        runningPrograms.update(programs => programs.filter(p => p != self));
        self.$destroy();
    }

    export let options = {
        title: 'Control Panel',
        width: 600,
        height: 400,
        icon: '/images/xp/icons/ControlPanel.png',
        id,
        exec_path
    };

    let items = [
        {name:'Display', icon:'/images/xp/icons/DisplayProperties.png', path:'./programs/display_properties.svelte'},
        {name:'Add or Remove Programs', icon:'/images/xp/icons/Programs.png', path:'./programs/app_installer.svelte'},
        {name:'Volume', icon:'/images/xp/icons/Volume.png', path:'./programs/volume_adjust.svelte'}
    ];

    function open(item){
        queueProgram.set({path:item.path, ...(item.fs_item?{fs_item:item.fs_item}:{})});
    }
</script>

<Window bind:this={window} on_click_close={destroy} options={options}>
    <div slot="content" class="p-4 grid grid-cols-3 gap-4 text-center select-none">
        {#each items as item}
            <div class="flex flex-col items-center cursor-pointer" on:dblclick={() => open(item)}>
                <img src={item.icon} class="w-12 h-12 mb-2" alt={item.name} />
                <span class="text-xs">{item.name}</span>
            </div>
        {/each}
    </div>
</Window>
